<template><div><div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token operator">&lt;</span>script setup lang<span class="token operator">=</span><span class="token string">"ts"</span><span class="token operator">></span></span>
<span class="line">  <span class="token keyword">import</span> <span class="token punctuation">{</span> LoremIpsum <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'lorem-ipsum'</span></span>
<span class="line">  <span class="token keyword">import</span> <span class="token punctuation">{</span> SortableOptions <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'sortablejs'</span></span>
<span class="line">  <span class="token keyword">import</span> <span class="token punctuation">{</span> computed<span class="token punctuation">,</span> reactive <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'vue'</span></span>
<span class="line"></span>
<span class="line">  <span class="token keyword">import</span> <span class="token punctuation">{</span> avatars <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'../assets/avatars'</span></span>
<span class="line"></span>
<span class="line">  <span class="token keyword">import</span> PrioritySvg <span class="token keyword">from</span> <span class="token string">'./shared/PrioritySvg.vue'</span></span>
<span class="line">  <span class="token keyword">import</span> UKanban <span class="token keyword">from</span> <span class="token string">'./UKanban.vue'</span></span>
<span class="line">  <span class="token keyword">import</span> <span class="token punctuation">{</span> KanbanColumn<span class="token punctuation">,</span> UKanbanResult <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./uKanbanTypes'</span></span>
<span class="line"></span>
<span class="line">  <span class="token keyword">const</span> lorem <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">LoremIpsum</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">  <span class="token keyword">function</span> <span class="token function">generateMockData</span><span class="token punctuation">(</span>col<span class="token operator">:</span> <span class="token builtin">number</span><span class="token punctuation">,</span> row<span class="token operator">:</span> <span class="token builtin">number</span><span class="token punctuation">)</span><span class="token operator">:</span> KanbanColumn<span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">const</span> result <span class="token operator">=</span> <span class="token generic-function"><span class="token function">reactive</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token builtin">any</span><span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">let</span> itemId <span class="token operator">=</span> <span class="token number">1</span></span>
<span class="line">    <span class="token keyword">let</span> columnId <span class="token operator">=</span> <span class="token number">1</span></span>
<span class="line">    <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> col<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">      <span class="token keyword">const</span> items <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span></span>
<span class="line">      <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> row<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">        items<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">          id<span class="token operator">:</span> itemId<span class="token punctuation">,</span></span>
<span class="line">          avatar<span class="token operator">:</span> avatars<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">          priority<span class="token operator">:</span> <span class="token string">'High'</span><span class="token punctuation">,</span></span>
<span class="line">          branch<span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">TT-</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>itemId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">-task-</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>itemId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span></span>
<span class="line">          title<span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Task-</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>itemId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span></span>
<span class="line">          task<span class="token operator">:</span> lorem<span class="token punctuation">.</span><span class="token function">generateSentences</span><span class="token punctuation">(</span>Math<span class="token punctuation">.</span><span class="token function">floor</span><span class="token punctuation">(</span>Math<span class="token punctuation">.</span><span class="token function">random</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">        itemId<span class="token operator">++</span></span>
<span class="line">      <span class="token punctuation">}</span></span>
<span class="line">      result<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">        status<span class="token operator">:</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">Column-</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>columnId<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span></span>
<span class="line">        items<span class="token punctuation">,</span></span>
<span class="line">      <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">      columnId<span class="token operator">++</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">    <span class="token keyword">return</span> result</span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token keyword">const</span> options <span class="token operator">=</span> <span class="token generic-function"><span class="token function">computed</span><span class="token generic class-name"><span class="token operator">&lt;</span>SortableOptions<span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token punctuation">{</span></span>
<span class="line">      group<span class="token operator">:</span> <span class="token punctuation">{</span> name<span class="token operator">:</span> <span class="token string">'group'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">      animation<span class="token operator">:</span> <span class="token number">300</span><span class="token punctuation">,</span></span>
<span class="line">      swapThreshold<span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span></span>
<span class="line">      forceFallback<span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">  <span class="token keyword">function</span> <span class="token function">onUpdate</span><span class="token punctuation">(</span>value<span class="token operator">:</span> UKanbanResult<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token string">'update'</span><span class="token punctuation">,</span> value<span class="token punctuation">)</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token operator">&lt;</span><span class="token operator">/</span>script<span class="token operator">></span></span>
<span class="line"></span>
<span class="line"><span class="token operator">&lt;</span>template<span class="token operator">></span></span>
<span class="line">  <span class="token operator">&lt;</span>div <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"wrapp"</span><span class="token operator">></span></span>
<span class="line">    <span class="token operator">&lt;</span>UKanban</span>
<span class="line">      <span class="token operator">:</span>columns<span class="token operator">=</span><span class="token string">"generateMockData(5, 3)"</span></span>
<span class="line">      <span class="token operator">:</span>options<span class="token operator">=</span><span class="token string">"options"</span></span>
<span class="line">      <span class="token decorator"><span class="token at operator">@</span><span class="token function">update</span></span><span class="token operator">=</span><span class="token string">"onUpdate"</span></span>
<span class="line">    <span class="token operator">></span></span>
<span class="line">      <span class="token operator">&lt;</span>template #item<span class="token operator">=</span><span class="token string">"{ elem }"</span><span class="token operator">></span></span>
<span class="line">        <span class="token operator">&lt;</span>div</span>
<span class="line">          <span class="token operator">:</span>key<span class="token operator">=</span><span class="token string">"elem.id"</span></span>
<span class="line">          <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"draggable"</span></span>
<span class="line">        <span class="token operator">></span></span>
<span class="line">          <span class="token operator">&lt;</span>div <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"app-card"</span><span class="token operator">></span></span>
<span class="line">            <span class="token operator">&lt;</span>div <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"app-card-header"</span><span class="token operator">></span></span>
<span class="line">              <span class="token operator">&lt;</span>h4<span class="token operator">></span><span class="token punctuation">{</span><span class="token punctuation">{</span> elem<span class="token punctuation">.</span>title <span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>h4<span class="token operator">></span></span>
<span class="line">              <span class="token operator">&lt;</span>div <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"app-card-task"</span><span class="token operator">></span><span class="token punctuation">{</span><span class="token punctuation">{</span> elem<span class="token punctuation">.</span>task <span class="token punctuation">}</span><span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span></span>
<span class="line">            <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span></span>
<span class="line">            <span class="token operator">&lt;</span>div <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"app-card-bottom"</span><span class="token operator">></span></span>
<span class="line">              <span class="token operator">&lt;</span>PrioritySvg <span class="token operator">:</span>priority<span class="token operator">=</span><span class="token string">"elem.priority"</span> <span class="token operator">/</span><span class="token operator">></span></span>
<span class="line">              <span class="token operator">&lt;</span>div <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"app-card-footer"</span><span class="token operator">></span></span>
<span class="line">                <span class="token operator">&lt;</span>div <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"app-card-branch"</span><span class="token operator">></span></span>
<span class="line">                  <span class="token punctuation">{</span><span class="token punctuation">{</span> elem<span class="token punctuation">.</span>branch <span class="token punctuation">}</span><span class="token punctuation">}</span></span>
<span class="line">                <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span></span>
<span class="line">                <span class="token operator">&lt;</span>img</span>
<span class="line">                  <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"app-card-avatar"</span></span>
<span class="line">                  <span class="token operator">:</span>src<span class="token operator">=</span><span class="token string">"elem.avatar"</span></span>
<span class="line">                  alt<span class="token operator">=</span><span class="token string">""</span></span>
<span class="line">                <span class="token operator">/</span><span class="token operator">></span></span>
<span class="line">              <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span></span>
<span class="line">            <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span></span>
<span class="line">          <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span></span>
<span class="line">        <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span></span>
<span class="line">      <span class="token operator">&lt;</span><span class="token operator">/</span>template<span class="token operator">></span></span>
<span class="line">    <span class="token operator">&lt;</span><span class="token operator">/</span>UKanban<span class="token operator">></span></span>
<span class="line">  <span class="token operator">&lt;</span><span class="token operator">/</span>div<span class="token operator">></span></span>
<span class="line"><span class="token operator">&lt;</span><span class="token operator">/</span>template<span class="token operator">></span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


